version: '3'
services:
  kvrocks:
    image: apache/kvrocks:nightly
    restart: always
    container_name: kvrocks
    mem_limit: 2G
    memswap_limit: -1
    environment:
      KVROCKS_port: 16666
      KVROCKS_workers: 6
      KVROCKS_timeout: 360
      KVROCKS_rocksdb__enable_blob_files: "yes"
      KVROCKS_rocksdb__compression: zstd
      KVROCKS_rocksdb__read_options__async_io: yes
      KVROCKS_dir: /data
      KVROCKS_log_dir: /log
    volumes:
      - ./data:/data
      - ./log:/log
    ports:
      - 16666:16666
